#!/usr/bin/env tsx
/**
 * Build-time script to generate embedded file modules.
 *
 * This reads source files and generates TypeScript modules that export
 * their content as string constants. This allows the content to be
 * bundled into Bun compiled binaries without relying on __dirname/readFileSync.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const HOOKS_DIR = join(__dirname, "../src/cli/hooks");

/**
 * Escape a string for use in a template literal.
 * Handles backticks, backslashes, and ${} interpolations.
 */
function escapeForTemplateLiteral(content: string): string {
  return content
    .replace(/\\/g, "\\\\") // Escape backslashes first
    .replace(/`/g, "\\`") // Escape backticks
    .replace(/\$\{/g, "\\${"); // Escape template interpolations
}

function generateEmbeddedFile(
  sourceFile: string,
  outputFile: string,
  exportName: string,
): void {
  const sourcePath = join(HOOKS_DIR, sourceFile);
  const outputPath = join(HOOKS_DIR, outputFile);

  const content = readFileSync(sourcePath, "utf-8");
  const escaped = escapeForTemplateLiteral(content);

  const output = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/generate-embedded-files.ts
// Source: ${sourceFile}

export const ${exportName} = \`${escaped}\`;
`;

  writeFileSync(outputPath, output, "utf-8");
  console.log(`Generated ${outputFile} from ${sourceFile}`);
}

// Generate embedded files
generateEmbeddedFile(
  "claude-session.js",
  "claude-session.embedded.ts",
  "CLAUDE_SESSION_SCRIPT",
);

console.log("Done generating embedded files.");
